from __future__ import annotations

from typing import Any

from app.services.market.parameter_defaults import (
    MARKET_INTRADAY_ANOMALY_DEFAULTS,
    MARKET_SECTOR_PROXY_DEFAULTS,
    MARKET_SECTOR_ETF_T0_DEFAULTS,
)


LOW_BUY_STRATEGY_PREFILTER_DEFAULTS: dict[str, dict[str, Any]] = {
    "classic_retrace": {
        "max_board_count": 2,
        "min_retracement_days": 1,
        "max_retracement_days": 6,
        "min_volume_burst_ratio": 1.05,
        "max_support_distance_pct": 3.0,
        "min_close_to_ma10_ratio": 0.98,
        "max_distribution_risk_score": 6.0,
        "max_post_volume_ratio_relaxed": 1.22,
    },
    "ma_support": {
        "max_board_count": 2,
        "min_retracement_days": 1,
        "max_retracement_days": 8,
        "min_close_to_ma20_ratio": 0.988,
        "max_close_to_ma5_ma10_pct": 2.8,
        "max_close_to_ma20_pct": 2.2,
        "max_support_distance_pct": 2.8,
    },
    "first_board": {
        "required_board_count": 1,
        "min_retracement_days": 1,
        "max_retracement_days": 6,
        "min_volume_burst_ratio": 1.25,
        "max_close_above_board_high_pct": 4.5,
        "max_distribution_risk_score": 5.8,
    },
    "volume_shrink": {
        "max_board_count": 2,
        "min_retracement_days": 1,
        "max_retracement_days": 8,
        "min_volume_burst_ratio": 1.65,
        "max_latest_volume_ratio": 1.12,
        "max_post_volume_ratio": 1.15,
        "max_support_distance_pct": 2.8,
        "min_close_to_ma20_ratio": 0.995,
        "max_distribution_risk_score": 5.6,
    },
    "breakout_support": {
        "min_retracement_days": 1,
        "max_retracement_days": 8,
        "max_breakout_distance_pct": 3.8,
        "min_close_to_breakout_ratio": 0.978,
        "max_latest_change_pct": 4.2,
    },
    "deep_pullback": {
        "max_board_count": 2,
        "min_retracement_days": 2,
        "max_retracement_days": 10,
        "min_drawdown_from_board_pct": -10.5,
        "max_drawdown_from_board_pct": -1.8,
        "max_support_distance_ma20_pct": 5.2,
    },
    "trend_rebound": {
        "min_retracement_days": 1,
        "max_retracement_days": 8,
        "min_close_to_ma20_ratio": 0.992,
        "min_close_to_ma10_ratio": 0.982,
        "min_drawdown_from_board_pct": -10.5,
    },
    "limit_up_breakout_retrace": {
        "min_platform_days": 20,
        "min_retracement_days": 2,
        "max_retracement_days": 5,
        "min_volume_burst_ratio": 1.9,
        "min_breakout_pct": 1.0,
        "max_platform_range_pct": 35.0,
        "min_drawdown_pct": -10.0,
        "max_drawdown_pct": -3.0,
        "max_post_volume_ratio": 0.78,
        "max_latest_volume_ratio": 0.82,
        "max_support_distance_pct": 3.0,
        "min_board_amount": 150_000_000.0,
        "min_platform_hold_ratio": 0.995,
        "min_board_open_hold_ratio": 0.985,
    },
    "divergence_consensus": {
        "min_platform_days": 20,
        "min_retracement_days": 4,
        "max_retracement_days": 12,
        "min_board_amount": 180_000_000.0,
        "min_volume_burst_ratio": 1.8,
        "min_platform_breakout_pct": 0.8,
        "max_platform_range_pct": 38.0,
        "min_divergence_volume_ratio": 0.55,
        "min_consolidation_days": 2,
        "max_consolidation_days": 8,
        "max_consolidation_volume_ratio": 0.72,
        "min_consensus_volume_ratio": 1.45,
        "max_breakout_extension_pct": 8.5,
    },
    "late_session_strong_support": {
        "min_amount": 200_000_000.0,
        "min_retracement_days": 1,
        "max_retracement_days": 8,
        "min_latest_change_pct": -2.0,
        "max_latest_change_pct": 6.5,
        "max_support_distance_pct": 3.2,
        "max_latest_volume_ratio": 1.25,
        "max_post_volume_ratio": 1.15,
        "min_close_position_ratio": 0.55,
        "max_distribution_risk_score": 5.5,
    },
    "core_midcap_vwap_ma5_retrace": {
        "min_amount": 500_000_000.0,
        "min_retracement_days": 1,
        "max_retracement_days": 6,
        "min_latest_change_pct": -4.0,
        "max_latest_change_pct": 2.8,
        "max_ma_distance_pct": 1.8,
        "max_support_distance_pct": 2.2,
        "max_latest_volume_ratio": 1.15,
        "max_post_volume_ratio": 1.2,
        "max_distribution_risk_score": 5.5,
    },
    "sector_mainline_first_divergence_low_buy": {
        "max_board_count": 2,
        "min_amount": 200_000_000.0,
        "min_retracement_days": 1,
        "max_retracement_days": 5,
        "min_latest_change_pct": -6.0,
        "max_latest_change_pct": 2.8,
        "min_volume_burst_ratio": 1.4,
        "max_support_distance_pct": 3.0,
        "max_latest_volume_ratio": 1.25,
        "max_post_volume_ratio": 1.25,
        "max_distribution_risk_score": 5.8,
    },
    "mainline_limitup_shrink_retrace_reclaim": {
        "max_board_count": 2,
        "min_amount": 180_000_000.0,
        "min_retracement_days": 3,
        "max_retracement_days": 8,
        "min_latest_change_pct": -4.5,
        "max_latest_change_pct": 3.2,
        "min_volume_burst_ratio": 1.6,
        "max_latest_volume_ratio": 1.05,
        "max_post_volume_ratio": 0.95,
        "max_support_distance_pct": 2.4,
        "max_ma_confluence_pct": 2.2,
        "min_support_touch_count": 2,
        "min_close_to_ma5_ratio": 0.998,
        "max_close_above_ma5_pct": 2.5,
        "max_distribution_risk_score": 5.0,
    },
    "ma_channel_band": {
        "min_amount": 50_000_000.0,
        "min_platform_days": 20,
        "min_retracement_days": 2,
        "max_retracement_days": 14,
        "min_close_to_ma20_ratio": 0.96,
        "max_ma20_distance_pct": 3.2,
        "max_latest_volume_ratio": 1.2,
        "max_post_volume_ratio": 1.25,
        "max_distribution_risk_score": 6.5,
        "max_support_distance_pct": 3.8,
    },
    "leader_pullback_band": {
        "max_board_count": 3,
        "exclude_symbol_prefixes": ["300", "688"],
        "min_amount": 50_000_000.0,
        "min_retracement_days": 1,
        "max_retracement_days": 8,
        "min_volume_burst_ratio": 1.6,
        "max_support_distance_pct": 3.5,
        "max_latest_volume_ratio": 1.25,
        "max_post_volume_ratio": 1.25,
        "max_distribution_risk_score": 5.8,
        "min_close_to_ma20_ratio": 1.0,
    },
}


LOW_BUY_STRATEGY_EXECUTION_DEFAULTS: dict[str, dict[str, Any]] = {
    "classic_retrace": {
        "min_score": 82.0,
        "entry_low_multiplier": 0.992,
        "entry_high_multiplier": 1.008,
        "min_retracement_days": 1,
        "max_retracement_days": 6,
        "max_support_distance_pct": 2.8,
        "max_post_volume_ratio": 1.22,
        "min_latest_change_pct": -3.8,
        "max_latest_change_pct": 3.6,
        "min_board_low_reclaim_ratio": 0.985,
    },
    "ma_support": {
        "ma5_anchor_max_pct": 1.3,
        "ma10_anchor_max_pct": 1.8,
        "entry_low_multiplier": 0.993,
        "entry_high_multiplier": 1.005,
        "max_support_distance_pct": 2.45,
        "min_latest_change_pct": -1.6,
        "max_close_to_ma20_pct": 1.2,
    },
    "first_board": {
        "entry_low_multiplier": 0.995,
        "entry_high_multiplier": 1.004,
        "max_retracement_days": 6,
        "min_board_open_hold_ratio": 0.982,
        "max_distribution_risk_score": 5.2,
    },
    "volume_shrink": {
        "entry_low_multiplier": 0.992,
        "entry_high_multiplier": 1.006,
        "min_volume_burst_ratio": 1.5,
        "max_support_distance_pct": 2.35,
        "max_post_volume_ratio": 1.08,
        "max_latest_volume_ratio": 1.05,
        "min_close_to_ma20_ratio": 0.998,
        "max_distribution_risk_score": 5.0,
        "min_latest_change_pct": -1.6,
    },
    "late_session_strong_support": {
        "min_score": 84.0,
        "ma5_anchor_multiplier": 1.012,
        "ma10_anchor_multiplier": 0.995,
        "entry_low_multiplier": 0.994,
        "entry_high_multiplier": 1.004,
        "min_close_position_ratio": 0.60,
        "max_support_distance_pct": 2.4,
        "max_latest_volume_ratio": 1.05,
        "max_post_volume_ratio": 1.08,
        "max_distribution_risk_score": 4.8,
    },
    "core_midcap_vwap_ma5_retrace": {
        "min_score": 84.0,
        "entry_low_multiplier": 0.994,
        "entry_high_multiplier": 1.006,
        "max_ma_distance_pct": 1.5,
        "max_support_distance_pct": 1.8,
        "max_latest_volume_ratio": 1.05,
        "max_post_volume_ratio": 1.12,
        "max_distribution_risk_score": 4.8,
    },
    "sector_mainline_first_divergence_low_buy": {
        "min_score": 84.0,
        "entry_low_multiplier": 0.994,
        "entry_high_multiplier": 1.004,
        "max_retracement_days": 3,
        "max_support_distance_pct": 2.0,
        "max_latest_volume_ratio": 1.08,
        "max_post_volume_ratio": 1.10,
        "max_distribution_risk_score": 4.8,
    },
    "mainline_limitup_shrink_retrace_reclaim": {
        "min_score": 86.0,
        "entry_low_multiplier": 0.992,
        "entry_high_min_multiplier": 1.006,
        "ma_anchor_entry_high_multiplier": 1.018,
        "max_latest_volume_ratio": 0.98,
        "max_post_volume_ratio": 0.88,
        "max_support_distance_pct": 1.9,
        "max_ma_confluence_pct": 2.0,
        "min_support_touch_count": 2,
        "min_close_to_ma5_ratio": 1.0,
        "max_distribution_risk_score": 4.6,
    },
    "limit_up_breakout_retrace": {
        "min_score": 88.0,
        "entry_low_multiplier": 0.996,
        "platform_entry_high_multiplier": 1.006,
        "ma_entry_high_multiplier": 1.002,
        "min_close_to_ma5_ratio": 0.998,
        "min_volume_burst_ratio": 2.0,
        "min_breakout_pct": 1.2,
        "min_drawdown_pct": -8.5,
        "max_drawdown_pct": -3.5,
        "max_post_volume_ratio": 0.72,
        "max_latest_volume_ratio": 0.78,
        "max_support_distance_pct": 2.5,
        "min_board_amount": 200_000_000.0,
    },
    "divergence_consensus": {
        "min_score": 90.0,
        "entry_low_multiplier": 0.995,
        "entry_high_multiplier": 1.035,
        "min_consensus_volume_ratio": 1.55,
        "max_consolidation_volume_ratio": 0.66,
        "min_close_strength": 0.58,
        "max_distribution_risk_score": 5.5,
    },
    "ma_channel_band": {
        "min_score": 84.0,
        "entry_low_multiplier": 0.986,
        "entry_high_multiplier": 1.012,
        "min_close_to_ma20_ratio": 0.992,
        "max_close_to_ma20_pct": 2.4,
        "max_latest_volume_ratio": 1.05,
        "max_post_volume_ratio": 1.10,
        "max_distribution_risk_score": 4.8,
    },
    "leader_pullback_band": {
        "min_score": 86.0,
        "entry_low_multiplier": 0.99,
        "entry_high_multiplier": 1.012,
        "max_support_distance_pct": 2.6,
        "max_latest_volume_ratio": 1.10,
        "max_post_volume_ratio": 1.12,
        "max_distribution_risk_score": 4.8,
    },
    "breakout_support": {
        "entry_low_multiplier": 0.993,
        "entry_high_multiplier": 1.005,
        "max_breakout_distance_pct": 2.8,
        "min_close_to_breakout_ratio": 0.99,
        "min_latest_change_pct": -1.4,
    },
    "deep_pullback": {
        "entry_low_multiplier": 0.988,
        "entry_high_multiplier": 1.006,
        "min_drawdown_from_board_pct": -9.2,
        "max_drawdown_from_board_pct": -2.8,
        "max_support_distance_ma20_pct": 3.6,
        "min_latest_change_pct": -1.2,
    },
    "trend_rebound": {
        "entry_low_multiplier": 0.992,
        "entry_high_multiplier": 1.006,
        "min_retracement_days": 1,
        "max_support_distance_pct": 2.9,
        "min_close_to_ma10_ratio": 0.988,
        "min_latest_change_pct": -1.4,
    },
}


LOW_BUY_SCORING_DEFAULTS: dict[str, Any] = {
    "base_score": 70.0,
    "volume_burst_base": 1.2,
    "volume_burst_cap": 2.0,
    "volume_burst_weight": 8.0,
    "volume_shrink_base": 0.85,
    "volume_shrink_cap": 0.5,
    "volume_shrink_weight": 24.0,
    "support_distance_base": 2.4,
    "support_distance_weight": 4.5,
    "latest_change_base": 1.8,
    "latest_change_weight": 3.2,
    "retracement_bonus": {
        "1": 3.0,
        "2": 7.2,
        "3": 8.0,
        "4": 6.2,
        "5": 3.8,
        "6": 1.6,
        "7": 0.2,
        "8": -0.6,
        "9": -1.6,
        "10": -2.4,
    },
    "first_board_bonus": 6.0,
    "high_board_count_threshold": 3,
    "high_board_penalty": -4.0,
    "max_score": 99.0,
    "global_bonuses": {
        "strong_trend": 5.2,
        "hot_industry": 3.5,
        "shrink_staircase": 2.8,
    },
    "strategy_bonuses": {
        "ma_support": {"support_distance_max_pct": 1.6, "bonus": 4.0},
        "first_board": {"max_retracement_days": 3, "bonus": 5.0},
        "volume_shrink": {"min_volume_burst_ratio": 2.0, "bonus": 5.5},
        "late_session_strong_support": {
            "close_position_base": 0.55,
            "close_position_weight": 12.0,
            "positive_change_bonus": 3.0,
            "latest_volume_max": 0.95,
            "latest_volume_bonus": 2.5,
        },
        "core_midcap_vwap_ma5_retrace": {
            "strong_trend_bonus": 4.0,
            "trend_ok_bonus": 2.0,
            "ma_distance_base": 1.8,
            "ma_distance_weight": 2.5,
            "large_amount_threshold": 800_000_000.0,
            "large_amount_bonus": 2.5,
        },
        "sector_mainline_first_divergence_low_buy": {
            "first_board_bonus": 4.0,
            "non_first_board_bonus": 1.5,
            "post_volume_base": 1.2,
            "post_volume_weight": 4.0,
            "board_low_held_bonus": 2.5,
        },
        "mainline_limitup_shrink_retrace_reclaim": {
            "first_board_bonus": 4.0,
            "non_first_board_bonus": 1.5,
            "ma_confluence_base": 2.2,
            "ma_confluence_weight": 2.2,
            "support_touch_offset": 1,
            "support_touch_cap": 2,
            "support_touch_weight": 1.8,
            "post_volume_base": 0.95,
            "post_volume_weight": 8.0,
            "close_above_ma5_bonus": 3.0,
            "board_low_held_bonus": 2.0,
        },
        "ma_channel_band": {
            "ma20_distance_base": 3.2,
            "ma20_distance_weight": 2.0,
            "close_above_ma20_bonus": 3.0,
            "trend_ok_bonus": 2.0,
        },
        "leader_pullback_band": {
            "strong_trend_bonus": 4.0,
            "trend_ok_bonus": 1.5,
            "board_low_held_bonus": 3.0,
            "volume_burst_base": 1.5,
            "volume_burst_cap": 1.5,
            "volume_burst_weight": 2.5,
        },
        "breakout_support": {"breakout_distance_max_pct": 2.0, "bonus": 4.0},
        "limit_up_breakout_retrace": {
            "platform_breakout_min_pct": 2.0,
            "platform_breakout_bonus": 6.0,
            "post_volume_max": 0.68,
            "post_volume_bonus": 4.0,
            "reversal_candle_bonus": 4.0,
        },
        "divergence_consensus": {
            "breakout_bonus": 5.0,
            "no_breakout_penalty": -8.0,
            "volume_ratio_base": 1.4,
            "volume_ratio_cap": 1.2,
            "volume_ratio_weight": 4.0,
            "consolidation_volume_base": 0.72,
            "consolidation_volume_weight": 12.0,
            "close_strength_min": 0.68,
            "close_strength_bonus": 3.0,
            "hot_industry_bonus": 2.0,
        },
        "deep_pullback": {
            "min_drawdown_pct": -8.5,
            "max_drawdown_pct": -3.0,
            "bonus": 5.0,
        },
        "trend_rebound": {
            "min_retracement_days": 2,
            "bonus": 4.0,
        },
    },
}


LOW_BUY_THRESHOLD_DEFAULTS: dict[str, Any] = {
    "stop_loss_hard_multiplier": 0.988,
    "stop_loss_soft_multiplier": 0.992,
    "stop_loss_divergence_multiplier": 0.985,
    "entry_zone_half_width_pct": 0.008,
    "entry_zone_tolerance_pct": 0.015,
    "core_tier_weight": 1.0,
    "auxiliary_tier_weight": 0.65,
    "max_factor_bonus": 8.0,
    "deep_pullback_non_core_position_cap": 10.0,
    "min_daily_amount_core": 50_000_000.0,
    "min_daily_amount_auxiliary": 30_000_000.0,
    "pullback_health_optimal_days": [3, 4],
    "pullback_health_max_score": 94.0,
    "pullback_health_min_score": 48.0,
    "pullback_health_day_decay": 9.0,
    "trend_fatigue_strong_trend_block": 6.0,
    "min_signal_score_buy": 75,
    "min_tradability_score_buy": 70,
    "min_sample_size_reliable": 30,
    "min_sample_size_display": 20,
    "new_strategy_age_days": 90,
    "new_strategy_weight_reduction": 0.5,
    "max_symbols_quote_refresh": 60,
    "quote_refresh_interval_tier1": 30,
    "quote_refresh_interval_tier2": 60,
    "quote_refresh_interval_tier3": 120,
    "factor_weights": {
        "deep_pullback_factor": 1.0,
        "trend_rebound_factor": 0.8,
        "sector_density_factor": 1.2,
        "shrink_quality_factor": 1.0,
        "gap_risk_factor": 1.5,
        "volatility_regime_factor": 0.7,
        "time_efficiency_factor": 0.6,
        "signal_freshness_factor": 0.5,
        "sector_flow_factor": 0.7,
        "big_order_flow_factor": 0.4,
        "price_structure_factor": 0.9,
        "event_risk_factor": 0.6,
        "absorption_quality_factor": 0.5,
    },
}


LOW_BUY_AUTO_GOVERNANCE_DEFAULTS: dict[str, Any] = {
    "min_filled_signals": 20,
    "watch_health_threshold": 55.0,
    "pause_health_threshold": 35.0,
    "pause_stop_loss_rate_threshold": 32.0,
    "watch_stop_loss_rate_threshold": 24.0,
    "recovery_min_filled_signals": 50,
    "recovery_health_threshold": 65.0,
    "recovery_max_stop_loss_rate": 20.0,
    "recovery_watch_days": 5,
    "recovery_paused_days": 10,
    "health_score": {
        "avg_net_return_low": -2.0,
        "avg_net_return_high": 4.0,
        "avg_net_return_weight": 23.0,
        "profit_factor_low": 0.6,
        "profit_factor_high": 2.0,
        "profit_factor_weight": 18.0,
        "max_drawdown_abs_cap": 8.0,
        "max_drawdown_weight": 16.0,
        "filled_signals_cap": 50.0,
        "filled_signals_weight": 16.0,
        "net_win_rate_low": -20.0,
        "net_win_rate_high": 35.0,
        "net_win_rate_weight": 12.0,
        "market_adaptation_weight": 15.0,
        "stop_loss_excess_threshold": 18.0,
        "stop_loss_excess_cap": 30.0,
        "stop_loss_penalty_weight": 0.45,
        "not_filled_excess_threshold": 40.0,
        "not_filled_excess_cap": 40.0,
        "not_filled_penalty_weight": 0.18,
        "score_min": 0.0,
        "score_max": 100.0,
    },
    "market_adaptation": {
        "min_bucket_samples": 5,
        "empty_score": 0.45,
        "return_3d_low": -2.0,
        "return_3d_high": 3.0,
        "return_3d_weight": 0.45,
        "return_5d_low": -3.0,
        "return_5d_high": 4.0,
        "return_5d_weight": 0.25,
        "hit_rate_low": 35.0,
        "hit_rate_high": 68.0,
        "hit_rate_weight": 0.30,
        "weak_state_keywords": ["退潮", "风险释放", "轮动过快"],
        "weak_state_multiplier": 0.85,
    },
    "health_text": {
        "min_filled_signals": 20,
        "healthy_score": 75.0,
        "watch_score": 55.0,
        "restricted_score": 35.0,
    },
}


LOW_BUY_RESEARCH_LAYER_DEFAULTS: dict[str, Any] = {
    "hard_block": {
        "block_distribution_risk_score": 7.0,
        "reversal_distribution_risk_score": 5.0,
    },
    "limit_up_breakout_retrace": {
        "prefilter_board_count": 1,
        "prefilter_min_amount": 100_000_000.0,
        "prefilter_min_platform_days": 20,
        "prefilter_min_retracement_days": 1,
        "prefilter_max_retracement_days": 8,
        "prefilter_min_volume_burst_ratio": 1.5,
        "prefilter_min_platform_breakout_pct": 0.0,
        "prefilter_max_platform_range_pct": 50.0,
        "prefilter_max_support_distance_pct": 10.0,
        "prefilter_min_drawdown_pct": -12.0,
        "near_max_support_distance_pct": 4.0,
        "near_max_post_volume_ratio": 0.90,
        "near_max_latest_volume_ratio": 0.95,
        "near_min_platform_reclaim_ratio": 0.985,
        "near_max_distribution_risk_score": 5.8,
        "buy_max_support_distance_pct": 2.0,
        "buy_max_post_volume_ratio": 0.72,
        "buy_max_latest_volume_ratio": 0.80,
        "buy_min_board_open_hold_ratio": 0.985,
        "failed_min_amount": 150_000_000.0,
        "failed_max_platform_range_pct": 40.0,
        "near_miss_support_distance_low_pct": 2.0,
        "near_miss_support_distance_high_pct": 4.0,
        "near_miss_post_volume_low": 0.72,
        "near_miss_post_volume_high": 0.90,
        "near_miss_drawdown_low_pct": -3.0,
        "near_miss_drawdown_high_pct": 3.0,
    },
    "divergence_consensus": {
        "prefilter_board_count": 1,
        "prefilter_min_amount": 120_000_000.0,
        "prefilter_min_platform_days": 20,
        "prefilter_min_retracement_days": 2,
        "prefilter_max_retracement_days": 10,
        "prefilter_min_volume_burst_ratio": 1.5,
        "prefilter_max_platform_range_pct": 50.0,
        "prefilter_min_consolidation_days": 1,
        "near_min_consolidation_days": 2,
        "near_max_consolidation_days": 6,
        "near_max_consolidation_volume_ratio": 0.75,
        "near_min_consensus_volume_ratio": 1.35,
        "near_min_close_strength": 0.45,
        "near_max_divergence_distance_pct": 3.0,
        "near_min_consolidation_high_reclaim_ratio": 0.985,
        "near_max_distribution_risk_score": 5.5,
        "buy_max_consolidation_volume_ratio": 0.65,
        "buy_min_consensus_volume_ratio": 1.60,
        "buy_min_close_strength": 0.65,
        "buy_min_divergence_breakout_ratio": 1.01,
        "buy_max_divergence_extension_ratio": 1.05,
        "buy_max_distribution_risk_score": 4.5,
        "failed_min_amount": 180_000_000.0,
        "failed_min_divergence_volume_ratio": 0.55,
        "near_miss_volume_ratio_low": 1.35,
        "near_miss_volume_ratio_high": 1.60,
        "near_miss_consolidation_volume_low": 0.65,
        "near_miss_consolidation_volume_high": 0.75,
    },
}


LOW_BUY_HARD_RISK_DEFAULTS: dict[str, Any] = {
    "distribution_block_score": 7.0,
    "distribution_degrade_score": 5.6,
    "distribution_block_penalty": 10.0,
    "distribution_degrade_penalty": 5.0,
    "volume_selloff_latest_volume_ratio": 2.4,
    "volume_selloff_latest_change_pct": -2.5,
    "volume_selloff_penalty": 4.5,
    "trend_break_ma60_ratio": 0.985,
    "trend_break_penalty": 4.0,
    "limit_up_change_pct": 9.7,
    "limit_up_close_position_ratio": 0.92,
    "limit_down_change_pct": -9.7,
    "limit_down_close_position_ratio": 0.12,
    "amount_missing_penalty": 5.0,
    "amount_block_threshold": 80_000_000.0,
    "amount_block_penalty": 12.0,
    "amount_degrade_threshold": 150_000_000.0,
    "amount_degrade_penalty": 4.0,
}


LOW_BUY_DYNAMIC_ADJUSTMENT_DEFAULTS: dict[str, Any] = {
    "market_floor_shift": {
        "broad_rally": -1.2,
        "repair": -0.4,
        "weight_support_active": 0.6,
        "low_volume_wait": 1.0,
        "fast_rotation": 1.8,
        "weight_support": 2.2,
        "high_flyer_retreat": 3.2,
        "risk_release": 5.0,
        "default": 1.0,
    },
    "risk_degrade_shift": 2.4,
    "risk_block_shift": 99.0,
    "leader_floor_shift": -0.7,
    "leader_position_multiplier": 1.04,
    "laggard_floor_shift": 1.0,
    "laggard_position_multiplier": 0.88,
    "factor_bonus_floor_weight": 0.16,
    "factor_bonus_floor_cap": 0.8,
    "score_floor_min": -2.0,
    "score_floor_max": 99.0,
    "soft_buy_shift_min": -1.5,
    "soft_buy_shift_max": 6.0,
    "soft_buy_shift_multiplier": 0.55,
    "position_multiplier_min": 0.0,
    "position_multiplier_max": 1.2,
    "performance_min_filled": 50,
    "performance_reliability_window": 50.0,
    "net_win_rate_weight": 0.0175,
    "avg_return_weight": 0.08,
    "drawdown_penalty_threshold": -6.0,
    "drawdown_penalty": 0.8,
    "floor_shift_positive_cap": 2.2,
    "floor_shift_negative_cap": -2.8,
    "position_edge_weight": 0.035,
    "position_edge_positive_cap": 0.12,
    "position_edge_negative_cap": -0.18,
}


POSITION_T_SCORING_DEFAULTS: dict[str, Any] = {
    "version": "quant-scoring-v1",
    "base_scores": {
        "positive": 35.0,
        "negative": 30.0,
        "risk": 25.0,
    },
    "action_thresholds": {
        "positive": 60.0,
        "negative": 62.0,
        "scenario_shifts": {
            "open_price_discovery": 5.0,
            "midday_consolidation": 2.0,
            "closing_repricing": 1.0,
        },
        "risk_level_shifts": {
            "high": 4.0,
            "low": -2.0,
        },
    },
    "risk_level_thresholds": {
        "high": 65.0,
        "medium": 38.0,
    },
    "positive_score": {
        "ma5_support": 10.0,
        "ma5_above_ma20": 8.0,
        "ma20_above_ma60": 6.0,
        "rsi_low": 44.0,
        "rsi_high": 62.0,
        "rsi_band_bonus": 10.0,
        "macd_non_negative_bonus": 8.0,
        "vwap_support_distance_pct": 0.006,
        "vwap_support_bonus": 12.0,
        "sector_alignment_threshold": 52.0,
        "sector_alignment_bonus": 5.0,
        "buy_pressure_threshold": 52.0,
        "buy_pressure_bonus": 4.0,
        "slope10_min": -0.3,
        "slope10_bonus": 5.0,
        "false_breakout_penalty": 10.0,
        "intraday_reversal_penalty": 6.0,
        "stall_after_volume_penalty": 4.0,
        "distribution_risk_weight": 0.45,
        "distribution_risk_cap": 4.5,
    },
    "negative_score": {
        "ma5_distance_multiplier": 1.005,
        "ma5_distance_bonus": 8.0,
        "high_rsi_threshold": 68.0,
        "high_rsi_bonus": 12.0,
        "macd_negative_bonus": 8.0,
        "vwap_distance_multiplier": 1.008,
        "vwap_distance_bonus": 12.0,
        "high_amplitude_threshold": 3.0,
        "high_amplitude_bonus": 8.0,
        "sector_alignment_threshold": 54.0,
        "sector_weak_bonus": 5.0,
        "sell_pressure_threshold": 52.0,
        "sell_pressure_bonus": 5.0,
        "false_breakout_bonus": 8.0,
        "intraday_reversal_bonus": 5.5,
        "stall_after_volume_bonus": 4.0,
        "distribution_risk_weight": 0.35,
        "distribution_risk_cap": 3.5,
    },
    "risk_score": {
        "amplitude_floor": 5.0,
        "amplitude_weight": 4.0,
        "atr_weight": 3.0,
        "tradability_floor": 55.0,
        "tradability_weight": 0.6,
        "sector_alignment_floor": 50.0,
        "sector_alignment_weight": 0.25,
        "event_medium_penalty": 6.0,
        "event_high_penalty": 15.0,
    },
}


POSITION_T_DECISION_DEFAULTS: dict[str, Any] = {
    "near_threshold_offset": 8.0,
    "near_score_gap": 2.0,
    "scene_override_shift": 3.0,
    "max_single_loss_floor_pct": 0.2,
    "default_max_single_loss_pct": 1.0,
    "light_min_ratio_floor": 0.8,
    "light_min_ratio_discount": 0.22,
    "lot_size": 100,
    "min_position_pct_for_cost": 5.0,
    "light_position_multiplier": 0.45,
    "light_position_min_pct": 5.0,
    "light_position_etf_cap_pct": 10.0,
    "light_position_stock_cap_pct": 8.0,
    "market_default_state": "low_volume_wait",
    "market_default_ranking_bonus": -2.0,
    "market_default_position_multiplier": 0.75,
    "market_default_buy_signal_penalty": 1.5,
    "market_default_t_threshold_shift": 0.12,
    "market_default_positive_threshold_shift": 2.0,
    "market_default_negative_threshold_shift": 2.0,
    "market_shift_base_weight": 0.55,
    "market_shift_strength_weight": 0.45,
    "market_position_min_multiplier": 0.35,
    "market_position_max_multiplier": 1.2,
    "market_etf_defense_bonus": 0.12,
    "market_etf_weight_support_profit_multiplier": 0.45,
    "market_etf_weight_support_active_profit_multiplier": 0.7,
    "market_etf_risk_release_profit_multiplier": 0.65,
    "market_etf_defense_risk_reward_multiplier": 0.6,
    "market_min_risk_reward_shift": {
        "broad_rally": -0.05,
        "repair": -0.02,
        "low_volume_wait": 0.03,
        "fast_rotation": 0.05,
        "weight_support": 0.08,
        "weight_support_active": 0.03,
        "high_flyer_retreat": 0.10,
        "risk_release": 0.15,
    },
    "execution_costs": {
        "slippage_liquidity_score_floor": 60.0,
        "slippage_liquidity_penalty_weight": 0.18,
        "slippage_medium_risk_add_bps": 1.5,
        "slippage_high_risk_add_bps": 3.5,
        "slippage_min_bps": 2.0,
        "slippage_max_bps": 25.0,
        "tradability_bonus_tiers": [
            {"min_score": 76.0, "bonus_pct": 0.45},
            {"min_score": 64.0, "bonus_pct": 0.28},
            {"min_score": 56.0, "bonus_pct": 0.16},
        ],
        "amplitude_bonus_tiers": [
            {"min_pct": 0.0, "max_pct": 2.0, "bonus_pct": 0.20},
            {"min_pct": 0.0, "max_pct": 2.8, "bonus_pct": 0.12},
        ],
        "stock_amount_bonus_threshold": 150_000_000.0,
        "stock_amount_bonus_pct": 0.25,
        "liquidity_bonus_tiers": [
            {"min_amount": 800_000_000.0, "etf_bonus_pct": 0.25, "stock_bonus_pct": 0.38},
            {"min_amount": 400_000_000.0, "etf_bonus_pct": 0.18, "stock_bonus_pct": 0.25},
            {"min_amount": 250_000_000.0, "etf_bonus_pct": 0.12, "stock_bonus_pct": 0.12},
        ],
        "min_profit_floor_etf_pct": 0.6,
        "min_profit_floor_stock_pct": 1.5,
        "light_profit_base_pct": {"etf": 0.48, "weight_stock": 0.86, "thematic_stock": 1.12},
        "light_profit_floor_pct": {"etf": 0.38, "weight_stock": 0.72, "thematic_stock": 0.72},
        "light_profit_positive_state_discount_pct": {"etf": 0.08, "weight_stock": 0.05, "thematic_stock": 0.05},
        "light_profit_weak_state_add_pct": {"etf": 0.08, "weight_stock": 0.15, "thematic_stock": 0.15},
        "net_profit_floor_pct": {
            "etf": {"positive_t": 0.25, "negative_t": 0.25},
            "weight_stock": {"positive_t": 0.50, "negative_t": 0.45},
            "thematic_stock": {"positive_t": 0.90, "negative_t": 0.80},
        },
    },
    "scene_resolution": {
        "distribution_risk_block_score": 7.2,
        "overheat_price_ma5_multiplier": 1.008,
        "overheat_price_vwap_multiplier": 1.006,
        "overheat_rsi_floor": 66.0,
        "overheat_amplitude_floor_pct": 3.0,
        "overheat_sell_pressure_floor": 52.0,
        "overheat_weak_sector_ceiling": 52.0,
        "trend_last_price_ma20_multiplier": 0.995,
        "trend_ma5_ma20_multiplier": 0.998,
        "trend_vwap_multiplier": 0.993,
        "trend_buy_pressure_floor": 48.0,
        "trend_sector_alignment_floor": 45.0,
    },
    "direction_gates": {
        "positive": {
            "default": {
                "price_extension_limit": 1.035,
                "weak_vwap_limit": 0.992,
                "slope_floor": -0.26,
                "weak_sector_floor": 44.0,
                "weak_buy_pressure_floor": 44.0,
            },
            "state_overrides": {
                "etf.weight_support": {
                    "price_extension_limit": 1.042,
                    "weak_vwap_limit": 0.989,
                    "slope_floor": -0.34,
                },
                "etf.weight_support_active": {
                    "price_extension_limit": 1.038,
                    "weak_vwap_limit": 0.991,
                    "slope_floor": -0.30,
                },
                "weight_stock.weight_support": {
                    "price_extension_limit": 1.040,
                    "weak_vwap_limit": 0.990,
                    "slope_floor": -0.32,
                    "weak_sector_floor": 38.0,
                    "weak_buy_pressure_floor": 40.0,
                },
                "weight_stock.weight_support_active": {
                    "price_extension_limit": 1.037,
                    "weak_vwap_limit": 0.991,
                    "slope_floor": -0.28,
                    "weak_sector_floor": 40.0,
                    "weak_buy_pressure_floor": 41.0,
                },
                "thematic_stock.weight_support": {
                    "price_extension_limit": 1.029,
                    "weak_vwap_limit": 0.995,
                    "slope_floor": -0.16,
                    "weak_sector_floor": 48.0,
                    "weak_buy_pressure_floor": 48.0,
                },
                "thematic_stock.weight_support_active": {
                    "price_extension_limit": 1.032,
                    "weak_vwap_limit": 0.993,
                    "weak_sector_floor": 42.0,
                    "weak_buy_pressure_floor": 42.0,
                },
                "thematic_stock.fast_rotation": {
                    "price_extension_limit": 1.028,
                    "weak_vwap_limit": 0.995,
                    "slope_floor": -0.08,
                    "weak_sector_floor": 50.0,
                    "weak_buy_pressure_floor": 50.0,
                },
                "weight_stock.high_flyer_retreat": {
                    "price_extension_limit": 1.032,
                    "weak_vwap_limit": 0.994,
                    "weak_sector_floor": 42.0,
                    "weak_buy_pressure_floor": 44.0,
                },
                "weight_stock.risk_release": {
                    "price_extension_limit": 1.032,
                    "weak_vwap_limit": 0.994,
                    "weak_sector_floor": 42.0,
                    "weak_buy_pressure_floor": 44.0,
                },
                "thematic_stock.high_flyer_retreat": {
                    "price_extension_limit": 1.026,
                    "weak_vwap_limit": 0.996,
                    "slope_floor": -0.10,
                    "weak_sector_floor": 48.0,
                    "weak_buy_pressure_floor": 48.0,
                },
                "thematic_stock.risk_release": {
                    "price_extension_limit": 1.026,
                    "weak_vwap_limit": 0.996,
                    "slope_floor": -0.10,
                    "weak_sector_floor": 48.0,
                    "weak_buy_pressure_floor": 48.0,
                },
            },
            "required_structure": "pullback_acceptance",
            "reclaim_vwap_multiplier": 1.001,
            "ma20_floor_multiplier": 0.992,
            "weak_vwap_slope_floor": -0.12,
            "weight_stock_support_states": ["weight_support", "weight_support_active"],
        },
        "positive_distribution_block": {
            "etf_reversal_score": 8.2,
            "stock_reversal_score": 7.0,
            "etf_distribution_score": 8.8,
            "stock_distribution_score": 7.8,
            "weak_stall_states": ["fast_rotation", "high_flyer_retreat", "risk_release"],
        },
        "thematic_state_block": {
            "blocked_states": ["fast_rotation", "high_flyer_retreat", "risk_release"],
            "sector_floor": 55.0,
            "buy_pressure_floor": 55.0,
        },
        "negative_buyback_room": {
            "min_distance_pct": {"etf": 0.35, "weight_stock": 0.55, "thematic_stock": 0.75},
            "distribution_bias_multiplier": 0.75,
            "near_high_multiplier": 0.988,
            "near_high_distribution_multiplier": 0.982,
            "estimated_buyback_multiplier": 0.998,
            "round_trip_cost_pct": {"etf": 0.12, "weight_stock": 0.22, "thematic_stock": 0.28},
            "min_net_room_pct": {"etf": 0.28, "weight_stock": 0.42, "thematic_stock": 0.55},
        },
    },
    "common": {
        "tradability_amount_cap": 40.0,
        "tradability_amount_divisor": 100_000_000.0,
        "tradability_amplitude_base": 30.0,
        "tradability_amplitude_target": 4.0,
        "tradability_amplitude_weight": 4.0,
        "tradability_volume_base": 20.0,
        "tradability_volume_target": 1.8,
        "tradability_volume_weight": 8.0,
        "tradability_atr_cap": 10.0,
        "tradability_atr_weight": 4.0,
        "event_penalty": {"low": 4.0, "medium": 10.0, "high": 22.0},
    },
    "blocking": {
        "min_tradability_score": 42.0,
        "limit_near_ratio": 0.90,
        "event_penalty_block": 25.0,
    },
}


MARKET_REGIME_SCORING_DEFAULTS: dict[str, Any] = {
    "normalizers": {
        "positive_ratio": [0.35, 0.75],
        "stock_up_ratio": [0.38, 0.72],
        "top3_avg_change": [0.15, 1.65],
        "median_change": [-0.20, 0.95],
        "stock_median_change": [-0.60, 1.40],
        "limit_down_value": [12.0, 50.0],
        "negative_median_change": [-0.2, 1.8],
        "negative_stock_median_change": [-0.3, 2.4],
        "weak_stock_up_gap": [-0.08, 0.30],
        "style_divergence": [0.40, 3.20],
        "largecap_change": [0.10, 2.20],
        "negative_smallcap_change": [-0.30, 2.40],
        "weight_stock_up_gap": [-0.05, 0.28],
        "concentration": [0.60, 2.30],
        "hot_turnover": [0.15, 1.0],
        "hot_overlap_gap": [0.0, 0.58],
        "rotation_top3_change": [0.50, 1.90],
        "rotation_positive_ratio": [0.28, 0.58],
        "limit_up_count": [8.0, 70.0],
        "board_height": [2.0, 7.0],
        "promotion_ratio": [0.08, 0.56],
        "promotion_break_gap": [-0.08, 0.22],
        "high_flyer_retreat_ratio": [0.06, 0.46],
        "broken_board_ratio": [0.10, 0.58],
        "retreat_limit_down_value": [10.0, 42.0],
        "promotion_break_pressure": [0.30, 0.86],
        "high_flyer_gap_speed": [0.10, 0.82],
        "distribution_stock_up_gap": [0.0, 0.32],
        "regime_score": [38.0, 78.0],
    },
    "mainline_lifecycle": {
        "retreat_high_flyer_ratio": 0.28,
        "retreat_distribution_pressure": 62.0,
        "rotation_hot_turnover": 0.55,
        "rotation_hot_overlap_max": 0.18,
        "accelerating_board_height": 4,
        "accelerating_promotion_ratio": 0.32,
        "accelerating_hot_overlap": 0.38,
        "stable_hot_overlap": 0.35,
    },
    "state_selection": {
        "repair_low_volume_max_gap": 3.0,
        "weight_support_active_max_gap": 4.0,
    },
    "confidence": {
        "breadth_ready_weight": 0.34,
        "emotion_ready_weight": 0.24,
        "base": 0.24,
        "score_weight": 0.34,
        "pressure_penalty_weight": 0.16,
    },
    "sector_proxy": MARKET_SECTOR_PROXY_DEFAULTS,
}


def quant_parameter_schema() -> dict[str, Any]:
    """Return a lightweight machine-readable schema for editable parameters."""

    return {
        "low_buy.strategy_prefilters": {
            strategy: {key: _field_schema(value) for key, value in params.items()}
            for strategy, params in LOW_BUY_STRATEGY_PREFILTER_DEFAULTS.items()
        },
        "low_buy.strategy_execution": {
            strategy: {key: _field_schema(value) for key, value in params.items()}
            for strategy, params in LOW_BUY_STRATEGY_EXECUTION_DEFAULTS.items()
        },
        "low_buy.scoring": _nested_schema(LOW_BUY_SCORING_DEFAULTS),
        "low_buy.thresholds": _nested_schema(LOW_BUY_THRESHOLD_DEFAULTS),
        "low_buy.auto_governance": _nested_schema(LOW_BUY_AUTO_GOVERNANCE_DEFAULTS),
        "low_buy.research_layers": _nested_schema(LOW_BUY_RESEARCH_LAYER_DEFAULTS),
        "low_buy.hard_risk": _nested_schema(LOW_BUY_HARD_RISK_DEFAULTS),
        "low_buy.dynamic_adjustment": _nested_schema(LOW_BUY_DYNAMIC_ADJUSTMENT_DEFAULTS),
        "low_buy.market_state_rules": {
            "default_state_rules": {"type": "object", "default": {}, "description": "市场状态默认规则覆盖。", "risk_level": "high"},
            "strategy_overrides": {"type": "object", "default": {}, "description": "按策略和市场状态覆盖执行规则。", "risk_level": "high"},
            "severity_penalty_scale": {"type": "object", "default": {}, "description": "市场强度惩罚系数覆盖。", "risk_level": "high"},
            "directional_bias": {"type": "object", "default": {}, "description": "正T/反T方向偏置阈值覆盖。", "risk_level": "high"},
        },
        "position_t.scoring": _nested_schema(POSITION_T_SCORING_DEFAULTS),
        "position_t.decision": _nested_schema(POSITION_T_DECISION_DEFAULTS),
        "market.regime_scoring": _nested_schema(MARKET_REGIME_SCORING_DEFAULTS),
        "market.sector_etf_t0": _nested_schema(MARKET_SECTOR_ETF_T0_DEFAULTS),
        "market.intraday_anomaly": _nested_schema(MARKET_INTRADAY_ANOMALY_DEFAULTS),
    }


def _field_schema(value: Any) -> dict[str, Any]:
    if isinstance(value, list):
        return {
            "type": "array",
            "default": value,
            "description": "策略运行参数，修改后下一次扫描生效。",
            "risk_level": "medium",
        }
    kind = "number" if isinstance(value, float) else "integer" if isinstance(value, int) else "string"
    return {
        "type": kind,
        "default": value,
        "min": 0 if isinstance(value, (int, float)) and value >= 0 else None,
        "max": None,
        "description": "策略运行参数，修改后下一次扫描生效。",
        "risk_level": "medium",
    }


def _nested_schema(values: dict[str, Any]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in values.items():
        if isinstance(value, dict):
            result[key] = _nested_schema(value)
        elif isinstance(value, list):
            result[key] = {
                "type": "array",
                "default": value,
                "description": "策略运行参数，修改后下一次扫描生效。",
                "risk_level": "medium",
            }
        else:
            result[key] = _field_schema(value)
    return result
