from __future__ import annotations

from typing import Any

LOW_BUY_STRATEGY_EXECUTION_DEFAULTS: dict[str, dict[str, Any]] = {
    "classic_retrace": {
        "min_score": 82.0,
        "entry_low_multiplier": 0.992,
        "entry_high_multiplier": 1.008,
        "min_retracement_days": 1,
        "max_retracement_days": 6,
        "max_support_distance_pct": 2.8,
        "max_post_volume_ratio": 1.22,
        "min_latest_change_pct": -3.8,
        "max_latest_change_pct": 3.6,
        "min_board_low_reclaim_ratio": 0.985,
    },
    "ma_support": {
        "ma5_anchor_max_pct": 1.3,
        "ma10_anchor_max_pct": 1.8,
        "entry_low_multiplier": 0.993,
        "entry_high_multiplier": 1.005,
        "max_support_distance_pct": 2.45,
        "min_latest_change_pct": -1.6,
        "max_close_to_ma20_pct": 1.2,
    },
    "first_board": {
        "entry_low_multiplier": 0.995,
        "entry_high_multiplier": 1.004,
        "max_retracement_days": 6,
        "min_board_open_hold_ratio": 0.982,
        "max_distribution_risk_score": 5.2,
    },
    "volume_shrink": {
        "entry_low_multiplier": 0.992,
        "entry_high_multiplier": 1.006,
        "min_volume_burst_ratio": 1.5,
        "max_support_distance_pct": 2.35,
        "max_post_volume_ratio": 1.08,
        "max_latest_volume_ratio": 1.05,
        "min_close_to_ma20_ratio": 0.998,
        "max_distribution_risk_score": 5.0,
        "min_latest_change_pct": -1.6,
    },
    "late_session_strong_support": {
        "min_score": 84.0,
        "ma5_anchor_multiplier": 1.012,
        "ma10_anchor_multiplier": 0.995,
        "entry_low_multiplier": 0.994,
        "entry_high_multiplier": 1.004,
        "min_close_position_ratio": 0.60,
        "max_support_distance_pct": 2.4,
        "max_latest_volume_ratio": 1.05,
        "max_post_volume_ratio": 1.08,
        "max_distribution_risk_score": 4.8,
    },
    "core_midcap_vwap_ma5_retrace": {
        "min_score": 84.0,
        "entry_low_multiplier": 0.994,
        "entry_high_multiplier": 1.006,
        "max_ma_distance_pct": 1.5,
        "max_support_distance_pct": 1.8,
        "max_latest_volume_ratio": 1.05,
        "max_post_volume_ratio": 1.12,
        "max_distribution_risk_score": 4.8,
    },
    "sector_mainline_first_divergence_low_buy": {
        "min_score": 84.0,
        "entry_low_multiplier": 0.994,
        "entry_high_multiplier": 1.004,
        "max_retracement_days": 3,
        "max_support_distance_pct": 2.0,
        "max_latest_volume_ratio": 1.08,
        "max_post_volume_ratio": 1.10,
        "max_distribution_risk_score": 4.8,
    },
    "mainline_limitup_shrink_retrace_reclaim": {
        "min_score": 86.0,
        "entry_low_multiplier": 0.992,
        "entry_high_min_multiplier": 1.006,
        "ma_anchor_entry_high_multiplier": 1.018,
        "max_latest_volume_ratio": 0.98,
        "max_post_volume_ratio": 0.88,
        "max_support_distance_pct": 1.9,
        "max_ma_confluence_pct": 2.0,
        "min_support_touch_count": 2,
        "min_close_to_ma5_ratio": 1.0,
        "max_distribution_risk_score": 4.6,
    },
    "limit_up_breakout_retrace": {
        "min_score": 88.0,
        "entry_low_multiplier": 0.996,
        "platform_entry_high_multiplier": 1.006,
        "ma_entry_high_multiplier": 1.002,
        "min_close_to_ma5_ratio": 0.998,
        "min_volume_burst_ratio": 2.0,
        "min_breakout_pct": 1.2,
        "min_drawdown_pct": -8.5,
        "max_drawdown_pct": -3.5,
        "max_post_volume_ratio": 0.72,
        "max_latest_volume_ratio": 0.78,
        "max_support_distance_pct": 2.5,
        "min_board_amount": 200_000_000.0,
    },
    "divergence_consensus": {
        "min_score": 90.0,
        "entry_low_multiplier": 0.995,
        "entry_high_multiplier": 1.035,
        "min_consensus_volume_ratio": 1.55,
        "max_consolidation_volume_ratio": 0.66,
        "min_close_strength": 0.58,
        "max_distribution_risk_score": 5.5,
    },
    "ma_channel_band": {
        "min_score": 84.0,
        "entry_low_multiplier": 0.986,
        "entry_high_multiplier": 1.012,
        "min_close_to_ma20_ratio": 0.992,
        "max_close_to_ma20_pct": 2.4,
        "max_latest_volume_ratio": 1.05,
        "max_post_volume_ratio": 1.10,
        "max_distribution_risk_score": 4.8,
    },
    "leader_pullback_band": {
        "min_score": 86.0,
        "entry_low_multiplier": 0.99,
        "entry_high_multiplier": 1.012,
        "max_support_distance_pct": 2.6,
        "max_latest_volume_ratio": 1.10,
        "max_post_volume_ratio": 1.12,
        "max_distribution_risk_score": 4.8,
    },
    "n_pattern_long_wash": {
        "min_score": 84.0,
        "entry_low_multiplier": 0.996,
        "entry_high_multiplier": 1.012,
        "min_retracement_days": 7,
        "max_retracement_days": 15,
        "min_board_low_hold_ratio": 1.005,
        "max_post_volume_ratio": 0.72,
        "min_repair_to_wash_volume_ratio": 1.2,
        "max_latest_volume_ratio": 1.25,
        "min_latest_change_pct": 0.8,
        "min_close_position_ratio": 0.60,
        "max_distribution_risk_score": 4.8,
        "setup_max_post_volume_ratio": 0.90,
        "setup_max_latest_volume_ratio": 1.45,
        "setup_min_latest_change_pct": -0.5,
        "setup_min_close_position_ratio": 0.45,
        "setup_max_distribution_risk_score": 5.2,
        "confirmation_min_board_low_hold_ratio": 1.0,
        "confirmation_max_post_volume_ratio": 0.90,
        "confirmation_min_repair_to_wash_volume_ratio": 1.08,
        "confirmation_max_latest_volume_ratio": 1.35,
        "confirmation_min_close_position_ratio": 0.50,
        "confirmation_min_latest_change_pct": -0.3,
        "confirmation_ma_reclaim_ratio": 0.995,
        "require_ma_reclaim": True,
        "allowed_market_states": ["broad_rally", "repair"],
        "hot_industry_tiers": ["core_hot", "secondary_hot"],
    },
    "n_pattern_short_wash": {
        "min_score": 84.0,
        "entry_low_multiplier": 0.996,
        "entry_high_multiplier": 1.008,
        "min_retracement_days": 2,
        "max_retracement_days": 5,
        "min_board_low_hold_ratio": 1.0,
        "max_latest_volume_ratio": 0.92,
        "max_support_distance_pct": 3.2,
        "min_close_position_ratio": 0.58,
        "max_distribution_risk_score": 4.8,
        "max_divergence_upper_shadow_ratio": 0.32,
        "setup_max_latest_volume_ratio": 1.15,
        "setup_max_support_distance_pct": 4.5,
        "setup_min_close_position_ratio": 0.45,
        "setup_max_distribution_risk_score": 5.2,
        "setup_upper_shadow_volume_ratio": 0.9,
        "confirmation_min_board_low_hold_ratio": 1.0,
        "confirmation_max_latest_volume_ratio": 1.0,
        "confirmation_max_support_distance_pct": 4.0,
        "confirmation_min_close_position_ratio": 0.48,
        "confirmation_max_upper_shadow_ratio": 0.38,
        "allowed_market_states": ["broad_rally", "repair"],
        "hot_industry_tiers": ["core_hot", "secondary_hot"],
    },
    "breakout_support": {
        "entry_low_multiplier": 0.993,
        "entry_high_multiplier": 1.005,
        "max_breakout_distance_pct": 2.8,
        "min_close_to_breakout_ratio": 0.99,
        "min_latest_change_pct": -1.4,
    },
    "deep_pullback": {
        "entry_low_multiplier": 0.988,
        "entry_high_multiplier": 1.006,
        "min_drawdown_from_board_pct": -9.2,
        "max_drawdown_from_board_pct": -2.8,
        "max_support_distance_ma20_pct": 3.6,
        "min_latest_change_pct": -1.2,
    },
    "trend_rebound": {
        "entry_low_multiplier": 0.992,
        "entry_high_multiplier": 1.006,
        "min_retracement_days": 1,
        "max_support_distance_pct": 2.9,
        "min_close_to_ma10_ratio": 0.988,
        "min_latest_change_pct": -1.4,
    },
}
