from __future__ import annotations

from typing import Any

LOW_BUY_SCORING_DEFAULTS: dict[str, Any] = {
    "base_score": 70.0,
    "volume_burst_base": 1.2,
    "volume_burst_cap": 2.0,
    "volume_burst_weight": 8.0,
    "volume_shrink_base": 0.85,
    "volume_shrink_cap": 0.5,
    "volume_shrink_weight": 24.0,
    "support_distance_base": 2.4,
    "support_distance_weight": 4.5,
    "latest_change_base": 1.8,
    "latest_change_weight": 3.2,
    "retracement_bonus": {
        "1": 3.0,
        "2": 7.2,
        "3": 8.0,
        "4": 6.2,
        "5": 3.8,
        "6": 1.6,
        "7": 0.2,
        "8": -0.6,
        "9": -1.6,
        "10": -2.4,
    },
    "first_board_bonus": 6.0,
    "high_board_count_threshold": 3,
    "high_board_penalty": -4.0,
    "max_score": 99.0,
    "global_bonuses": {
        "strong_trend": 5.2,
        "hot_industry": 3.5,
        "shrink_staircase": 2.8,
        "multi_timeframe_resonance": 5.0,
    },
    "strategy_bonuses": {
        "ma_support": {"support_distance_max_pct": 1.6, "bonus": 4.0},
        "first_board": {"max_retracement_days": 3, "bonus": 5.0},
        "volume_shrink": {"min_volume_burst_ratio": 2.0, "bonus": 5.5},
        "late_session_strong_support": {
            "close_position_base": 0.55,
            "close_position_weight": 12.0,
            "positive_change_bonus": 3.0,
            "latest_volume_max": 0.95,
            "latest_volume_bonus": 2.5,
        },
        "core_midcap_vwap_ma5_retrace": {
            "strong_trend_bonus": 4.0,
            "trend_ok_bonus": 2.0,
            "ma_distance_base": 1.8,
            "ma_distance_weight": 2.5,
            "large_amount_threshold": 800_000_000.0,
            "large_amount_bonus": 2.5,
        },
        "sector_mainline_first_divergence_low_buy": {
            "first_board_bonus": 4.0,
            "non_first_board_bonus": 1.5,
            "post_volume_base": 1.2,
            "post_volume_weight": 4.0,
            "board_low_held_bonus": 2.5,
        },
        "mainline_limitup_shrink_retrace_reclaim": {
            "first_board_bonus": 4.0,
            "non_first_board_bonus": 1.5,
            "ma_confluence_base": 2.2,
            "ma_confluence_weight": 2.2,
            "support_touch_offset": 1,
            "support_touch_cap": 2,
            "support_touch_weight": 1.8,
            "post_volume_base": 0.95,
            "post_volume_weight": 8.0,
            "close_above_ma5_bonus": 3.0,
            "board_low_held_bonus": 2.0,
        },
        "ma_channel_band": {
            "ma20_distance_base": 3.2,
            "ma20_distance_weight": 2.0,
            "close_above_ma20_bonus": 3.0,
            "trend_ok_bonus": 2.0,
        },
        "leader_pullback_band": {
            "strong_trend_bonus": 4.0,
            "trend_ok_bonus": 1.5,
            "board_low_held_bonus": 3.0,
            "volume_burst_base": 1.5,
            "volume_burst_cap": 1.5,
            "volume_burst_weight": 2.5,
        },
        "n_pattern_long_wash": {
            "board_low_held_bonus": 3.0,
            "post_volume_base": 0.82,
            "post_volume_weight": 10.0,
            "close_position_base": 0.50,
            "close_position_weight": 8.0,
            "long_wash_day_min": 8,
            "long_wash_day_bonus": 2.0,
        },
        "n_pattern_short_wash": {
            "board_low_held_bonus": 2.5,
            "reversal_candle_bonus": 4.0,
            "close_position_base": 0.45,
            "close_position_weight": 7.0,
            "short_wash_day_max": 4,
            "short_wash_day_bonus": 2.0,
        },
        "breakout_support": {"breakout_distance_max_pct": 2.0, "bonus": 4.0},
        "limit_up_breakout_retrace": {
            "platform_breakout_min_pct": 2.0,
            "platform_breakout_bonus": 6.0,
            "post_volume_max": 0.68,
            "post_volume_bonus": 4.0,
            "reversal_candle_bonus": 4.0,
        },
        "divergence_consensus": {
            "breakout_bonus": 5.0,
            "no_breakout_penalty": -8.0,
            "volume_ratio_base": 1.4,
            "volume_ratio_cap": 1.2,
            "volume_ratio_weight": 4.0,
            "consolidation_volume_base": 0.72,
            "consolidation_volume_weight": 12.0,
            "close_strength_min": 0.68,
            "close_strength_bonus": 3.0,
            "hot_industry_bonus": 2.0,
        },
        "deep_pullback": {
            "min_drawdown_pct": -8.5,
            "max_drawdown_pct": -3.0,
            "bonus": 5.0,
        },
        "trend_rebound": {
            "min_retracement_days": 2,
            "bonus": 4.0,
        },
    },
}

LOW_BUY_THRESHOLD_DEFAULTS: dict[str, Any] = {
    "stop_loss_hard_multiplier": 0.988,
    "stop_loss_soft_multiplier": 0.992,
    "stop_loss_divergence_multiplier": 0.985,
    "entry_zone_half_width_pct": 0.008,
    "entry_zone_tolerance_pct": 0.015,
    "core_tier_weight": 1.0,
    "auxiliary_tier_weight": 0.65,
    "max_factor_bonus": 8.0,
    "deep_pullback_non_core_position_cap": 10.0,
    "min_daily_amount_core": 50_000_000.0,
    "min_daily_amount_auxiliary": 30_000_000.0,
    "pullback_health_optimal_days": [3, 4],
    "pullback_health_max_score": 94.0,
    "pullback_health_min_score": 48.0,
    "pullback_health_day_decay": 9.0,
    "trend_fatigue_strong_trend_block": 6.0,
    "min_signal_score_buy": 75,
    "min_tradability_score_buy": 70,
    "min_sample_size_reliable": 30,
    "min_sample_size_display": 20,
    "new_strategy_age_days": 90,
    "new_strategy_weight_reduction": 0.5,
    "max_symbols_quote_refresh": 60,
    "quote_refresh_interval_tier1": 30,
    "quote_refresh_interval_tier2": 60,
    "quote_refresh_interval_tier3": 120,
    "selection_quality_volume_max": 0.88,
    "selection_quality_ma20_distance_min": 5.0,
    "selection_quality_ma20_distance_max": 12.0,
    "selection_quality_distribution_risk_max": 5.5,
    "selection_quality_volume_burst_min": 1.35,
    "factor_weights": {
        "deep_pullback_factor": 1.0,
        "trend_rebound_factor": 0.8,
        "sector_density_factor": 1.2,
        "shrink_quality_factor": 1.0,
        "gap_risk_factor": 1.5,
        "volatility_regime_factor": 0.7,
        "time_efficiency_factor": 0.6,
        "signal_freshness_factor": 0.5,
        "sector_flow_factor": 0.7,
        "big_order_flow_factor": 0.4,
        "price_structure_factor": 0.9,
        "event_risk_factor": 0.6,
        "absorption_quality_factor": 0.5,
        "selection_quality_factor": 0.8,
    },
}

LOW_BUY_AUTO_GOVERNANCE_DEFAULTS: dict[str, Any] = {
    "min_filled_signals": 20,
    "watch_health_threshold": 55.0,
    "pause_health_threshold": 35.0,
    "pause_stop_loss_rate_threshold": 32.0,
    "watch_stop_loss_rate_threshold": 24.0,
    "recovery_min_filled_signals": 50,
    "recovery_health_threshold": 65.0,
    "recovery_max_stop_loss_rate": 20.0,
    "recovery_watch_days": 5,
    "recovery_paused_days": 10,
    "evidence_gated_strategies": {
        "mainline_limitup_shrink_retrace_reclaim": {
            "min_filled_signals": 20,
            "status": "watch",
            "reason": "主线涨停回调仍处于生产观察期，真实成交样本不足，暂不放大为强买。",
        },
    },
    "health_score": {
        "avg_net_return_low": -2.0,
        "avg_net_return_high": 4.0,
        "avg_net_return_weight": 23.0,
        "profit_factor_low": 0.6,
        "profit_factor_high": 2.0,
        "profit_factor_weight": 18.0,
        "max_drawdown_abs_cap": 8.0,
        "max_drawdown_weight": 16.0,
        "filled_signals_cap": 50.0,
        "filled_signals_weight": 16.0,
        "net_win_rate_low": -20.0,
        "net_win_rate_high": 35.0,
        "net_win_rate_weight": 12.0,
        "market_adaptation_weight": 15.0,
        "stop_loss_excess_threshold": 18.0,
        "stop_loss_excess_cap": 30.0,
        "stop_loss_penalty_weight": 0.45,
        "not_filled_excess_threshold": 40.0,
        "not_filled_excess_cap": 40.0,
        "not_filled_penalty_weight": 0.18,
        "score_min": 0.0,
        "score_max": 100.0,
    },
    "market_adaptation": {
        "min_bucket_samples": 5,
        "empty_score": 0.45,
        "return_3d_low": -2.0,
        "return_3d_high": 3.0,
        "return_3d_weight": 0.45,
        "return_5d_low": -3.0,
        "return_5d_high": 4.0,
        "return_5d_weight": 0.25,
        "hit_rate_low": 35.0,
        "hit_rate_high": 68.0,
        "hit_rate_weight": 0.30,
        "weak_state_keywords": ["退潮", "风险释放", "轮动过快"],
        "weak_state_multiplier": 0.85,
    },
    "health_text": {
        "min_filled_signals": 20,
        "healthy_score": 75.0,
        "watch_score": 55.0,
        "restricted_score": 35.0,
    },
}
