from __future__ import annotations

from typing import Any

LOW_BUY_RESEARCH_LAYER_DEFAULTS: dict[str, Any] = {
    "hard_block": {
        "block_distribution_risk_score": 7.0,
        "reversal_distribution_risk_score": 5.0,
    },
    "limit_up_breakout_retrace": {
        "prefilter_board_count": 1,
        "prefilter_min_amount": 100_000_000.0,
        "prefilter_min_platform_days": 20,
        "prefilter_min_retracement_days": 1,
        "prefilter_max_retracement_days": 8,
        "prefilter_min_volume_burst_ratio": 1.5,
        "prefilter_min_platform_breakout_pct": 0.0,
        "prefilter_max_platform_range_pct": 50.0,
        "prefilter_max_support_distance_pct": 10.0,
        "prefilter_min_drawdown_pct": -12.0,
        "near_max_support_distance_pct": 4.0,
        "near_max_post_volume_ratio": 0.90,
        "near_max_latest_volume_ratio": 0.95,
        "near_min_platform_reclaim_ratio": 0.985,
        "near_max_distribution_risk_score": 5.8,
        "buy_max_support_distance_pct": 2.0,
        "buy_max_post_volume_ratio": 0.72,
        "buy_max_latest_volume_ratio": 0.80,
        "buy_min_board_open_hold_ratio": 0.985,
        "failed_min_amount": 150_000_000.0,
        "failed_max_platform_range_pct": 40.0,
        "near_miss_support_distance_low_pct": 2.0,
        "near_miss_support_distance_high_pct": 4.0,
        "near_miss_post_volume_low": 0.72,
        "near_miss_post_volume_high": 0.90,
        "near_miss_drawdown_low_pct": -3.0,
        "near_miss_drawdown_high_pct": 3.0,
    },
    "divergence_consensus": {
        "prefilter_board_count": 1,
        "prefilter_min_amount": 120_000_000.0,
        "prefilter_min_platform_days": 20,
        "prefilter_min_retracement_days": 2,
        "prefilter_max_retracement_days": 10,
        "prefilter_min_volume_burst_ratio": 1.5,
        "prefilter_max_platform_range_pct": 50.0,
        "prefilter_min_consolidation_days": 1,
        "near_min_consolidation_days": 2,
        "near_max_consolidation_days": 6,
        "near_max_consolidation_volume_ratio": 0.75,
        "near_min_consensus_volume_ratio": 1.35,
        "near_min_close_strength": 0.45,
        "near_max_divergence_distance_pct": 3.0,
        "near_min_consolidation_high_reclaim_ratio": 0.985,
        "near_max_distribution_risk_score": 5.5,
        "buy_max_consolidation_volume_ratio": 0.65,
        "buy_min_consensus_volume_ratio": 1.60,
        "buy_min_close_strength": 0.65,
        "buy_min_divergence_breakout_ratio": 1.01,
        "buy_max_divergence_extension_ratio": 1.05,
        "buy_max_distribution_risk_score": 4.5,
        "failed_min_amount": 180_000_000.0,
        "failed_min_divergence_volume_ratio": 0.55,
        "near_miss_volume_ratio_low": 1.35,
        "near_miss_volume_ratio_high": 1.60,
        "near_miss_consolidation_volume_low": 0.65,
        "near_miss_consolidation_volume_high": 0.75,
    },
}

LOW_BUY_HARD_RISK_DEFAULTS: dict[str, Any] = {
    "distribution_block_score": 7.0,
    "distribution_degrade_score": 5.6,
    "distribution_block_penalty": 10.0,
    "distribution_degrade_penalty": 5.0,
    "volume_selloff_latest_volume_ratio": 2.4,
    "volume_selloff_latest_change_pct": -2.5,
    "volume_selloff_penalty": 4.5,
    "trend_break_ma60_ratio": 0.985,
    "trend_break_penalty": 4.0,
    "limit_up_change_pct": 9.7,
    "limit_up_close_position_ratio": 0.92,
    "limit_down_change_pct": -9.7,
    "limit_down_close_position_ratio": 0.12,
    "amount_missing_penalty": 5.0,
    "amount_block_threshold": 80_000_000.0,
    "amount_block_penalty": 12.0,
    "amount_degrade_threshold": 150_000_000.0,
    "amount_degrade_penalty": 4.0,
}

LOW_BUY_DYNAMIC_ADJUSTMENT_DEFAULTS: dict[str, Any] = {
    "market_floor_shift": {
        "broad_rally": -1.2,
        "repair": -0.4,
        "weight_support_active": 0.6,
        "low_volume_wait": 1.0,
        "fast_rotation": 1.8,
        "weight_support": 2.2,
        "high_flyer_retreat": 3.2,
        "risk_release": 5.0,
        "default": 1.0,
    },
    "risk_degrade_shift": 2.4,
    "risk_block_shift": 99.0,
    "leader_floor_shift": -0.7,
    "leader_position_multiplier": 1.04,
    "laggard_floor_shift": 1.0,
    "laggard_position_multiplier": 0.88,
    "factor_bonus_floor_weight": 0.16,
    "factor_bonus_floor_cap": 0.8,
    "score_floor_min": -2.0,
    "score_floor_max": 99.0,
    "soft_buy_shift_min": -1.5,
    "soft_buy_shift_max": 6.0,
    "soft_buy_shift_multiplier": 0.55,
    "position_multiplier_min": 0.0,
    "position_multiplier_max": 1.2,
    "performance_min_filled": 50,
    "performance_reliability_window": 50.0,
    "net_win_rate_weight": 0.0175,
    "avg_return_weight": 0.08,
    "drawdown_penalty_threshold": -6.0,
    "drawdown_penalty": 0.8,
    "floor_shift_positive_cap": 2.2,
    "floor_shift_negative_cap": -2.8,
    "position_edge_weight": 0.035,
    "position_edge_positive_cap": 0.12,
    "position_edge_negative_cap": -0.18,
}
