from __future__ import annotations

from typing import Any

POSITION_T_SCORING_DEFAULTS: dict[str, Any] = {
    "version": "quant-scoring-v1",
    "score_min": 0.0,
    "score_max": 100.0,
    "base_scores": {
        "positive": 35.0,
        "negative": 30.0,
        "risk": 25.0,
    },
    "action_thresholds": {
        "positive": 60.0,
        "negative": 62.0,
        "scenario_shifts": {
            "open_price_discovery": 5.0,
            "midday_consolidation": 2.0,
            "closing_repricing": 1.0,
        },
        "risk_level_shifts": {
            "high": 4.0,
            "low": -2.0,
        },
    },
    "risk_level_thresholds": {
        "high": 65.0,
        "medium": 38.0,
    },
    "positive_score": {
        "ma5_support": 10.0,
        "ma5_above_ma20": 8.0,
        "ma20_above_ma60": 6.0,
        "rsi_low": 44.0,
        "rsi_high": 62.0,
        "rsi_band_bonus": 10.0,
        "macd_non_negative_bonus": 8.0,
        "vwap_support_distance_pct": 0.006,
        "vwap_support_bonus": 12.0,
        "sector_alignment_threshold": 52.0,
        "sector_alignment_bonus": 5.0,
        "buy_pressure_threshold": 52.0,
        "buy_pressure_bonus": 4.0,
        "slope10_min": -0.3,
        "slope10_bonus": 5.0,
        "false_breakout_penalty": 10.0,
        "intraday_reversal_penalty": 6.0,
        "stall_after_volume_penalty": 4.0,
        "distribution_risk_weight": 0.45,
        "distribution_risk_cap": 4.5,
    },
    "negative_score": {
        "ma5_distance_multiplier": 1.005,
        "ma5_distance_bonus": 8.0,
        "high_rsi_threshold": 68.0,
        "high_rsi_bonus": 12.0,
        "macd_negative_bonus": 8.0,
        "vwap_distance_multiplier": 1.008,
        "vwap_distance_bonus": 12.0,
        "high_amplitude_threshold": 3.0,
        "high_amplitude_bonus": 8.0,
        "sector_alignment_threshold": 54.0,
        "sector_weak_bonus": 5.0,
        "sell_pressure_threshold": 52.0,
        "sell_pressure_bonus": 5.0,
        "false_breakout_bonus": 8.0,
        "intraday_reversal_bonus": 5.5,
        "stall_after_volume_bonus": 4.0,
        "distribution_risk_weight": 0.35,
        "distribution_risk_cap": 3.5,
    },
    "risk_score": {
        "amplitude_floor": 5.0,
        "amplitude_weight": 4.0,
        "atr_weight": 3.0,
        "tradability_floor": 55.0,
        "tradability_weight": 0.6,
        "sector_alignment_floor": 50.0,
        "sector_alignment_weight": 0.25,
        "event_medium_penalty": 6.0,
        "event_high_penalty": 15.0,
    },
}

POSITION_T_DECISION_DEFAULTS: dict[str, Any] = {
    "near_threshold_offset": 8.0,
    "near_score_gap": 2.0,
    "scene_override_shift": 3.0,
    "max_single_loss_floor_pct": 0.2,
    "default_max_single_loss_pct": 1.0,
    "light_min_ratio_floor": 0.8,
    "light_min_ratio_discount": 0.22,
    "lot_size": 100,
    "min_position_pct_for_cost": 5.0,
    "light_position_multiplier": 0.45,
    "light_position_min_pct": 5.0,
    "light_position_etf_cap_pct": 10.0,
    "light_position_stock_cap_pct": 8.0,
    "market_default_state": "low_volume_wait",
    "market_default_ranking_bonus": -2.0,
    "market_default_position_multiplier": 0.75,
    "market_default_buy_signal_penalty": 1.5,
    "market_default_t_threshold_shift": 0.12,
    "market_default_positive_threshold_shift": 2.0,
    "market_default_negative_threshold_shift": 2.0,
    "market_shift_base_weight": 0.55,
    "market_shift_strength_weight": 0.45,
    "market_position_min_multiplier": 0.35,
    "market_position_max_multiplier": 1.2,
    "market_etf_defense_bonus": 0.12,
    "market_etf_weight_support_profit_multiplier": 0.45,
    "market_etf_weight_support_active_profit_multiplier": 0.7,
    "market_etf_risk_release_profit_multiplier": 0.65,
    "market_etf_defense_risk_reward_multiplier": 0.6,
    "market_min_risk_reward_shift": {
        "broad_rally": -0.05,
        "repair": -0.02,
        "low_volume_wait": 0.03,
        "fast_rotation": 0.05,
        "weight_support": 0.08,
        "weight_support_active": 0.03,
        "high_flyer_retreat": 0.10,
        "risk_release": 0.15,
    },
    "execution_costs": {
        "slippage_liquidity_score_floor": 60.0,
        "slippage_liquidity_penalty_weight": 0.18,
        "slippage_medium_risk_add_bps": 1.5,
        "slippage_high_risk_add_bps": 3.5,
        "slippage_min_bps": 2.0,
        "slippage_max_bps": 25.0,
        "tradability_bonus_tiers": [
            {"min_score": 76.0, "bonus_pct": 0.45},
            {"min_score": 64.0, "bonus_pct": 0.28},
            {"min_score": 56.0, "bonus_pct": 0.16},
        ],
        "amplitude_bonus_tiers": [
            {"min_pct": 0.0, "max_pct": 2.0, "bonus_pct": 0.20},
            {"min_pct": 0.0, "max_pct": 2.8, "bonus_pct": 0.12},
        ],
        "stock_amount_bonus_threshold": 150_000_000.0,
        "stock_amount_bonus_pct": 0.25,
        "liquidity_bonus_tiers": [
            {"min_amount": 800_000_000.0, "etf_bonus_pct": 0.25, "stock_bonus_pct": 0.38},
            {"min_amount": 400_000_000.0, "etf_bonus_pct": 0.18, "stock_bonus_pct": 0.25},
            {"min_amount": 250_000_000.0, "etf_bonus_pct": 0.12, "stock_bonus_pct": 0.12},
        ],
        "min_profit_floor_etf_pct": 0.6,
        "min_profit_floor_stock_pct": 1.5,
        "light_profit_base_pct": {"etf": 0.48, "weight_stock": 0.86, "thematic_stock": 1.12},
        "light_profit_floor_pct": {"etf": 0.38, "weight_stock": 0.72, "thematic_stock": 0.72},
        "light_profit_positive_state_discount_pct": {"etf": 0.08, "weight_stock": 0.05, "thematic_stock": 0.05},
        "light_profit_weak_state_add_pct": {"etf": 0.08, "weight_stock": 0.15, "thematic_stock": 0.15},
        "net_profit_floor_pct": {
            "etf": {"positive_t": 0.25, "negative_t": 0.25},
            "weight_stock": {"positive_t": 0.50, "negative_t": 0.45},
            "thematic_stock": {"positive_t": 0.90, "negative_t": 0.80},
        },
    },
    "scene_resolution": {
        "distribution_risk_block_score": 7.2,
        "overheat_price_ma5_multiplier": 1.008,
        "overheat_price_vwap_multiplier": 1.006,
        "overheat_rsi_floor": 66.0,
        "overheat_amplitude_floor_pct": 3.0,
        "overheat_sell_pressure_floor": 52.0,
        "overheat_weak_sector_ceiling": 52.0,
        "trend_last_price_ma20_multiplier": 0.995,
        "trend_ma5_ma20_multiplier": 0.998,
        "trend_vwap_multiplier": 0.993,
        "trend_buy_pressure_floor": 48.0,
        "trend_sector_alignment_floor": 45.0,
    },
    "direction_gates": {
        "positive": {
            "default": {
                "price_extension_limit": 1.035,
                "weak_vwap_limit": 0.992,
                "slope_floor": -0.26,
                "weak_sector_floor": 44.0,
                "weak_buy_pressure_floor": 44.0,
            },
            "state_overrides": {
                "etf.weight_support": {
                    "price_extension_limit": 1.042,
                    "weak_vwap_limit": 0.989,
                    "slope_floor": -0.34,
                },
                "etf.weight_support_active": {
                    "price_extension_limit": 1.038,
                    "weak_vwap_limit": 0.991,
                    "slope_floor": -0.30,
                },
                "weight_stock.weight_support": {
                    "price_extension_limit": 1.040,
                    "weak_vwap_limit": 0.990,
                    "slope_floor": -0.32,
                    "weak_sector_floor": 38.0,
                    "weak_buy_pressure_floor": 40.0,
                },
                "weight_stock.weight_support_active": {
                    "price_extension_limit": 1.037,
                    "weak_vwap_limit": 0.991,
                    "slope_floor": -0.28,
                    "weak_sector_floor": 40.0,
                    "weak_buy_pressure_floor": 41.0,
                },
                "thematic_stock.weight_support": {
                    "price_extension_limit": 1.029,
                    "weak_vwap_limit": 0.995,
                    "slope_floor": -0.16,
                    "weak_sector_floor": 48.0,
                    "weak_buy_pressure_floor": 48.0,
                },
                "thematic_stock.weight_support_active": {
                    "price_extension_limit": 1.032,
                    "weak_vwap_limit": 0.993,
                    "weak_sector_floor": 42.0,
                    "weak_buy_pressure_floor": 42.0,
                },
                "thematic_stock.fast_rotation": {
                    "price_extension_limit": 1.028,
                    "weak_vwap_limit": 0.995,
                    "slope_floor": -0.08,
                    "weak_sector_floor": 50.0,
                    "weak_buy_pressure_floor": 50.0,
                },
                "weight_stock.high_flyer_retreat": {
                    "price_extension_limit": 1.032,
                    "weak_vwap_limit": 0.994,
                    "weak_sector_floor": 42.0,
                    "weak_buy_pressure_floor": 44.0,
                },
                "weight_stock.risk_release": {
                    "price_extension_limit": 1.032,
                    "weak_vwap_limit": 0.994,
                    "weak_sector_floor": 42.0,
                    "weak_buy_pressure_floor": 44.0,
                },
                "thematic_stock.high_flyer_retreat": {
                    "price_extension_limit": 1.026,
                    "weak_vwap_limit": 0.996,
                    "slope_floor": -0.10,
                    "weak_sector_floor": 48.0,
                    "weak_buy_pressure_floor": 48.0,
                },
                "thematic_stock.risk_release": {
                    "price_extension_limit": 1.026,
                    "weak_vwap_limit": 0.996,
                    "slope_floor": -0.10,
                    "weak_sector_floor": 48.0,
                    "weak_buy_pressure_floor": 48.0,
                },
            },
            "required_structure": "pullback_acceptance",
            "reclaim_vwap_multiplier": 1.001,
            "ma20_floor_multiplier": 0.992,
            "weak_vwap_slope_floor": -0.12,
            "weight_stock_support_states": ["weight_support", "weight_support_active"],
        },
        "positive_distribution_block": {
            "etf_reversal_score": 8.2,
            "stock_reversal_score": 7.0,
            "etf_distribution_score": 8.8,
            "stock_distribution_score": 7.8,
            "weak_stall_states": ["fast_rotation", "high_flyer_retreat", "risk_release"],
        },
        "thematic_state_block": {
            "blocked_states": ["fast_rotation", "high_flyer_retreat", "risk_release"],
            "sector_floor": 55.0,
            "buy_pressure_floor": 55.0,
        },
        "negative_buyback_room": {
            "min_distance_pct": {"etf": 0.35, "weight_stock": 0.55, "thematic_stock": 0.75},
            "distribution_bias_multiplier": 0.75,
            "near_high_multiplier": 0.988,
            "near_high_distribution_multiplier": 0.982,
            "estimated_buyback_multiplier": 0.998,
            "round_trip_cost_pct": {"etf": 0.12, "weight_stock": 0.22, "thematic_stock": 0.28},
            "min_net_room_pct": {"etf": 0.28, "weight_stock": 0.42, "thematic_stock": 0.55},
        },
    },
    "common": {
        "tradability_amount_cap": 40.0,
        "tradability_amount_divisor": 100_000_000.0,
        "tradability_amplitude_base": 30.0,
        "tradability_amplitude_target": 4.0,
        "tradability_amplitude_weight": 4.0,
        "tradability_volume_base": 20.0,
        "tradability_volume_target": 1.8,
        "tradability_volume_weight": 8.0,
        "tradability_atr_cap": 10.0,
        "tradability_atr_weight": 4.0,
        "event_penalty": {"low": 4.0, "medium": 10.0, "high": 22.0},
    },
    "blocking": {
        "min_tradability_score": 42.0,
        "limit_near_ratio": 0.90,
        "event_penalty_block": 25.0,
    },
}
