from __future__ import annotations

from typing import Any


MARKET_SECTOR_ETF_T0_DEFAULTS: dict[str, Any] = {
    "priority_min_limit": 12,
    "priority_limit_multiplier": 3,
    "max_opportunities": 8,
    "entry_low_multiplier": 0.996,
    "entry_high_multiplier": 1.002,
    "sell_low_multiplier": 1.008,
    "sell_high_multiplier": 1.014,
    "stop_loss_multiplier": 0.992,
    "fee_edge_buffer_pct": 0.8,
    "positive_confidence_min": 60.0,
    "production_min_edge_pass": 2,
    "production_pass_rate_min_pct": 60.0,
    "production_min_settled_samples": 30,
    "production_min_success_rate_pct": 55.0,
    "production_max_p_value": 0.05,
    "shadow_min_samples": 30,
    "paper_auto_enabled": True,
    "paper_auto_max_orders": 2,
    "paper_auto_cash_pct": 0.12,
    "paper_auto_min_confidence": 68.0,
    "paper_auto_min_edge_pct": 0.9,
    "paper_auto_require_intraday_signal": True,
    "paper_auto_min_intraday_confidence": 62.0,
    "paper_auto_blocked_market_states": ["risk_release", "high_flyer_retreat"],
    "paper_auto_take_profit_pct": 1.2,
    "paper_auto_stop_loss_pct": -0.8,
    "paper_auto_time_exit_min_pct": 0.4,
    "signal_bar_limit": 120,
    "signal_min_bars": 20,
    "signal_bollinger_window": 20,
    "signal_bollinger_std": 2.0,
    "signal_rsi_period": 14,
    "signal_buy_vwap_deviation_pct": 0.35,
    "signal_sell_vwap_deviation_pct": 0.35,
    "signal_min_net_edge_pct": 0.12,
    "signal_oversold_rsi": 38.0,
    "signal_overbought_rsi": 64.0,
    "signal_max_volume_ratio": 3.5,
    "signal_min_volume_ratio": 0.2,
    "signal_max_trend_slope_abs_pct": 1.6,
    "signal_stop_loss_pct": -0.45,
    "signal_target_buffer_pct": 0.05,
    "signal_liquidity_intraday_amount_ratio": 0.02,
    "signal_tracking_divergence_block_pct": 1.6,
    "universe_overrides": {},
    "confidence_base": 45.0,
    "confidence_priority_floor": 75.0,
    "confidence_priority_weight": 0.8,
    "confidence_positive_market_bonus": 8.0,
    "confidence_negative_market_penalty": 20.0,
    "confidence_hot_change_threshold": 2.5,
    "confidence_hot_change_penalty": 8.0,
    "confidence_weak_change_threshold": -2.0,
    "confidence_weak_change_penalty": 6.0,
    "confidence_cap": 95.0,
    "sector_proxy_map": {
        "宽基": {"symbol": "510300", "name": "沪深300ETF"},
        "沪深300": {"symbol": "510300", "name": "沪深300ETF"},
        "大盘": {"symbol": "510300", "name": "沪深300ETF"},
        "创业板": {"symbol": "159915", "name": "创业板ETF"},
        "科创": {"symbol": "588000", "name": "科创50ETF"},
        "半导体": {"symbol": "512480", "name": "半导体ETF"},
        "芯片": {"symbol": "512760", "name": "芯片ETF"},
        "人工智能": {"symbol": "515000", "name": "科技ETF"},
        "算力": {"symbol": "515000", "name": "科技ETF"},
        "软件": {"symbol": "515000", "name": "科技ETF"},
        "军工": {"symbol": "512660", "name": "军工ETF"},
        "国防军工": {"symbol": "512660", "name": "军工ETF"},
        "证券": {"symbol": "512880", "name": "证券ETF"},
        "券商": {"symbol": "512880", "name": "证券ETF"},
        "金融": {"symbol": "512880", "name": "证券ETF"},
        "光伏": {"symbol": "515790", "name": "光伏ETF"},
        "新能源": {"symbol": "516160", "name": "新能源ETF"},
        "电力设备": {"symbol": "516160", "name": "新能源ETF"},
        "医疗": {"symbol": "512170", "name": "医疗ETF"},
        "医药": {"symbol": "512170", "name": "医疗ETF"},
        "消费": {"symbol": "510310", "name": "消费ETF"},
        "食品饮料": {"symbol": "510310", "name": "消费ETF"},
        "白酒": {"symbol": "512690", "name": "酒ETF"},
        "有色": {"symbol": "512400", "name": "有色金属ETF"},
        "有色金属": {"symbol": "512400", "name": "有色金属ETF"},
        "稀土": {"symbol": "516780", "name": "稀土ETF"},
        "房地产": {"symbol": "512200", "name": "房地产ETF"},
        "地产": {"symbol": "512200", "name": "房地产ETF"},
        "能源": {"symbol": "159930", "name": "能源ETF"},
        "煤炭": {"symbol": "515220", "name": "煤炭ETF"},
        "银行": {"symbol": "512800", "name": "银行ETF"},
    },
}


MARKET_INTRADAY_ANOMALY_DEFAULTS: dict[str, Any] = {
    "intraday_bar_limit": 60,
    "change_up_threshold_pct": 5.0,
    "change_up_score": 20.0,
    "change_down_threshold_pct": -4.0,
    "change_down_score": 18.0,
    "volume_ratio_threshold": 2.5,
    "volume_ratio_score": 14.0,
    "range_pct_threshold": 4.0,
    "range_score": 12.0,
    "high_retrace_threshold_pct": 2.0,
    "weak_close_position_max": 0.45,
    "retrace_score": 18.0,
    "strong_close_position_min": 0.72,
    "strong_change_min_pct": 1.5,
    "strong_stretch_score": 8.0,
    "volume_tail_count": 10,
    "volume_tail_min_count": 5,
    "volume_spike_multiplier": 2.0,
    "volume_spike_score": 10.0,
    "stale_data_score": 12.0,
    "high_level_score": 55.0,
    "medium_level_score": 32.0,
    "watch_level_score": 18.0,
    "validation_symbol_limit": 30,
    "validation_min_score": 18.0,
    "validation_min_samples": 5,
    "validation_pass_rate_min_pct": 80.0,
    "shadow_min_samples": 30,
    "production_min_success_rate_pct": 55.0,
    "production_max_p_value": 0.05,
}


MARKET_DISTRIBUTION_SIGNAL_DEFAULTS: dict[str, Any] = {
    "denominator_floor": 0.01,
    "doji_body_pct_max": 1.1,
    "shadow_ratio_threshold": 0.35,
    "weak_close_position_max": 0.38,
    "false_breakout_high_multiplier": 1.008,
    "false_breakout_close_multiplier": 0.996,
    "stall_volume_burst_min": 1.7,
    "stall_post_volume_min": 0.68,
    "stall_latest_volume_min": 0.36,
    "stall_abs_change_max_pct": 2.2,
    "stall_reference_close_multiplier": 0.995,
    "reversal_latest_change_max_pct": 1.8,
    "intraday_recent_high_window": 12,
    "intraday_close_window": 4,
    "intraday_recent_volume_window": 3,
    "intraday_previous_volume_window": 6,
    "intraday_volume_expansion_multiplier": 1.15,
    "intraday_false_breakout_high_multiplier": 1.006,
    "intraday_false_breakout_retrace_multiplier": 0.994,
    "intraday_false_breakout_vwap_multiplier": 0.999,
    "intraday_close_band_max": 0.004,
    "intraday_stall_high_multiplier": 1.003,
    "intraday_stall_close_multiplier": 0.998,
    "intraday_reversal_vwap_multiplier": 0.999,
    "score_false_breakout": 5.0,
    "score_stall_after_volume": 3.0,
    "score_intraday_reversal": 2.5,
    "score_upper_shadow_weight": 3.2,
    "score_upper_shadow_cap": 1.8,
    "score_weak_close": 0.8,
    "score_cap": 10.0,
}


POSITION_T_INTRADAY_STRUCTURE_DEFAULTS: dict[str, Any] = {
    "min_bars": 6,
    "recent_window": 5,
    "previous_window": 5,
    "pullback_anchor_multiplier": 1.004,
    "reclaim_vwap_multiplier": 1.001,
    "rising_lows_min_bars": 3,
    "volume_shrink_multiplier": 0.96,
    "avg_volume_floor": 1.0,
    "near_high_multiplier": 0.985,
    "extended_ma5_multiplier": 1.01,
    "extended_vwap_multiplier": 1.008,
    "pressure_distribution_risk_min": 4.8,
    "sharp_drop_vwap_break_multiplier": 0.988,
    "sharp_drop_reclaim_multiplier": 1.002,
    "range_contraction_min_bars": 3,
    "range_floor": 0.01,
    "range_contraction_day_range_multiplier": 0.28,
    "range_contraction_volume_multiplier": 0.9,
}


MARKET_SECTOR_PROXY_DEFAULTS: dict[str, Any] = {
    "score_min": 0.0,
    "score_max": 100.0,
    "etf_strength_bonus": 4.0,
    "growth_board_bonus": 2.0,
    "event_cache_hours": 3.0,
    "event_change_high_threshold_pct": 7.0,
    "event_volume_ratio_threshold": 2.5,
    "micro_min_price_range": 0.01,
    "micro_default_volume_ratio": 1.0,
    "micro_large_order_weight": 15.0,
    "board_change_base_score": 50.0,
    "board_change_weight": 8.0,
    "board_breadth_weight": 18.0,
    "board_change_pct_weight": 5.0,
    "board_leader_weight": 0.8,
    "board_turnover_weight": 1.2,
    "market_min_bars": 20,
    "market_ma_window": 20,
    "market_slope_window": 10,
    "market_denominator_floor": 0.01,
    "market_base_score": 50.0,
    "market_slope_weight": 2.2,
    "market_relative_weight": 3.0,
}
