#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
BACKEND = ROOT / "backend"
OUTPUT = ROOT / "frontend" / "src" / "generated" / "strategyMetaFallback.ts"


def main() -> int:
    sys.path.insert(0, str(BACKEND))
    from app.services.strategy_metadata_service import (  # noqa: PLC0415
        DEFAULT_STRATEGY_META,
        _strategy_tier,
        _strategy_tier_label,
    )

    items = []
    for seed in DEFAULT_STRATEGY_META:
        tier = _strategy_tier(seed)
        display_category = _strategy_tier_label(tier)
        items.append(
            {
                "key": seed.key,
                "name": seed.name,
                "display_name": seed.name,
                "label": seed.name,
                "description": seed.description,
                "tier": tier.value,
                "category_key": tier.value,
                "category": display_category,
                "display_category": display_category,
                "risk_level": seed.risk_level,
                "typical_holding_days": seed.typical_holding_days,
                "sort_order": seed.sort_order,
            }
        )

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(items, ensure_ascii=False, indent=2)
    OUTPUT.write_text(
        "// Generated by scripts/sync_strategy_meta_fallback.py. Do not edit manually.\n"
        f"export const GENERATED_STRATEGY_META_FALLBACK = {payload} as const;\n",
        encoding="utf-8",
    )
    print(f"synced {len(items)} strategy metadata fallback rows -> {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
