#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
BACKEND = ROOT / "backend"
OUTPUT = ROOT / "frontend" / "src" / "generated" / "strategyMetaFallback.ts"
VENV_SITE = sorted((BACKEND / ".venv" / "lib").glob("python*/site-packages"))


def main() -> int:
    parser = argparse.ArgumentParser(description="同步或校验前端策略元数据 fallback")
    parser.add_argument("--check", action="store_true", help="只校验生成结果是否与当前文件一致")
    args = parser.parse_args()
    content = _generated_content()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != content:
            print(
                "strategy metadata fallback drift detected; run "
                "`python scripts/sync_strategy_meta_fallback.py` to regenerate.",
                file=sys.stderr,
            )
            return 1
        print(f"strategy metadata fallback is up to date -> {OUTPUT.relative_to(ROOT)}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"synced strategy metadata fallback rows -> {OUTPUT.relative_to(ROOT)}")
    return 0


def _generated_content() -> str:
    sys.path.insert(0, str(BACKEND))
    for path in VENV_SITE:
        sys.path.insert(0, str(path))
    from app.services.strategy_metadata_service import (  # noqa: PLC0415
        DEFAULT_STRATEGY_META,
        _strategy_tier,
        _strategy_tier_label,
    )

    items = []
    for seed in DEFAULT_STRATEGY_META:
        tier = _strategy_tier(seed)
        display_category = _strategy_tier_label(tier)
        items.append(
            {
                "key": seed.key,
                "name": seed.name,
                "display_name": seed.name,
                "label": seed.name,
                "description": seed.description,
                "tier": tier.value,
                "category_key": tier.value,
                "category": display_category,
                "display_category": display_category,
                "risk_level": seed.risk_level,
                "typical_holding_days": seed.typical_holding_days,
                "sort_order": seed.sort_order,
                "enabled": seed.enabled,
                "probe_status": seed.probe_status,
                "probe_summary": seed.probe_summary,
                "visibility": seed.visibility,
            }
        )

    payload = json.dumps(items, ensure_ascii=False, indent=2)
    return (
        "// Generated by scripts/sync_strategy_meta_fallback.py. Do not edit manually.\n"
        f"export const GENERATED_STRATEGY_META_FALLBACK = {payload} as const;\n"
    )


if __name__ == "__main__":
    raise SystemExit(main())
