server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html-root;
    index index.html;

    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;

    location = /index.html {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
        try_files /index.html =404;
    }

    location = /next/index.html {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
        alias /usr/share/nginx/html-next/index.html;
    }

    location /next/assets/ {
        add_header Cache-Control "public, max-age=31536000, immutable";
        alias /usr/share/nginx/html-next/assets/;
        try_files $uri =404;
    }

    location /assets/ {
        add_header Cache-Control "public, max-age=31536000, immutable";
        try_files $uri =404;
    }

    location /next/ {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
        alias /usr/share/nginx/html-next/;
        try_files $uri $uri/ /index.html;
    }

    location / {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
        try_files $uri $uri/ /index.html;
    }
}
